# Generated by Django 4.2.24 on 2025-10-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('program_type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('TECHNICAL', 'Technical Skills'), ('SOFT_SKILLS', 'Soft Skills'), ('LEADERSHIP', 'Leadership'), ('COMPLIANCE', 'Compliance'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='program type')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='duration (hours)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='mandatory')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='provider')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='instructor')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training program',
                'verbose_name_plural': 'training programs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='certification name')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='issuing organization')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential URL')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='enrollment date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='ENROLLED', max_length=20, verbose_name='status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('certificate_url', models.URLField(blank=True, verbose_name='certificate URL')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingprogram')),
            ],
            options={
                'verbose_name': 'training enrollment',
                'verbose_name_plural': 'training enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('employee', 'program', 'enrollment_date')},
            },
        ),
    ]
