# Generated by Django 5.1.5 on 2026-03-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenant_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='certification name')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='issuing organization')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential URL')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('program_type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('TECHNICAL', 'Technical Skills'), ('SOFT_SKILLS', 'Soft Skills'), ('LEADERSHIP', 'Leadership'), ('COMPLIANCE', 'Compliance'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='program type')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='duration (hours)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='mandatory')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='provider')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='instructor')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('requires_approval', models.BooleanField(default=False, help_text='Department programs may require admin approval', verbose_name='requires admin approval')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_programs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for company-wide training', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='accounts.companydepartment', verbose_name='department')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'training program',
                'verbose_name_plural': 'training programs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=200, verbose_name='training title')),
                ('program_type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('TECHNICAL', 'Technical Skills'), ('SOFT_SKILLS', 'Soft Skills'), ('LEADERSHIP', 'Leadership'), ('COMPLIANCE', 'Compliance'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='program type')),
                ('description', models.TextField(verbose_name='description/justification')),
                ('target_employees', models.PositiveIntegerField(default=1, help_text='How many employees will attend', verbose_name='number of employees')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='estimated duration (hours)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('preferred_provider', models.CharField(blank=True, max_length=200, verbose_name='preferred provider')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('business_justification', models.TextField(help_text='Explain the business need and expected benefits', verbose_name='business justification')),
                ('urgency_reason', models.TextField(blank=True, help_text='Explain why this is urgent', verbose_name='urgency reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='approval date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_training', models.ForeignKey(blank=True, help_text='Training program created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='training.trainingprogram', verbose_name='created training program')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='accounts.companydepartment', verbose_name='department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'training request',
                'verbose_name_plural': 'training requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='enrollment date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='ENROLLED', max_length=20, verbose_name='status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('certificate_url', models.URLField(blank=True, verbose_name='certificate URL')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingprogram')),
            ],
            options={
                'verbose_name': 'training enrollment',
                'verbose_name_plural': 'training enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('tenant', 'employee', 'program', 'enrollment_date')},
            },
        ),
    ]
