# Generated by Django 4.2.24 on 2025-10-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_companybranch_employeeprofile_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('DRAWN', 'Drawn Signature'), ('TYPED', 'Typed Signature'), ('UPLOADED', 'Uploaded Image')], max_length=20)),
                ('signature_data', models.TextField(help_text='Base64 encoded signature or typed text')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('consent_text', models.TextField(help_text='Text that user agreed to when signing')),
                ('consented', models.BooleanField(default=False)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Signature Created'), ('VERIFIED', 'Signature Verified'), ('INVALIDATED', 'Signature Invalidated'), ('VIEWED', 'Signature Viewed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='eforms.esignature')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HR', 'HR Forms'), ('FINANCE', 'Finance Forms'), ('GENERAL', 'General Forms'), ('COMPLIANCE', 'Compliance Forms'), ('CUSTOM', 'Custom Forms')], default='GENERAL', max_length=20)),
                ('form_fields', models.JSONField(default=dict, help_text='JSON structure of form fields')),
                ('requires_signature', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approver_role', models.CharField(blank=True, help_text='Role required to approve (e.g., SUPERVISOR, HR)', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict, help_text='Submitted form data')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_forms', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='accounts.company')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='eforms.formtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text Input'), ('TEXTAREA', 'Text Area'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('DATE', 'Date'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio Button'), ('SELECT', 'Dropdown'), ('FILE', 'File Upload'), ('SIGNATURE', 'Signature')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/radio fields')),
                ('order', models.IntegerField(default=0)),
                ('width', models.CharField(default='full', help_text='full, half, third', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='eforms.formtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_approvals', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='eforms.formsubmission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='esignature',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='eforms.formsubmission'),
        ),
    ]
