# Generated by Django 4.2.24 on 2026-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0002_esignature_tenant_formapproval_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='header_style',
            field=models.CharField(choices=[('logo_left', 'Logo Left'), ('logo_center', 'Logo Center'), ('logo_right', 'Logo Right'), ('full_width', 'Full Width')], default='logo_left', help_text='Letterhead layout for this form', max_length=20),
        ),
    ]
