# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0002_alter_performancereview_reviewer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='performancefeedback',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='performancetemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='performancetemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='template name'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('tenant', 'employee', 'review_type', 'review_period_start', 'review_period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='performancetemplate',
            unique_together={('tenant', 'name')},
        ),
    ]
