# Generated by Django 4.2.28 on 2026-02-24 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0003_alter_performancereview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='competency name')),
                ('description', models.TextField(verbose_name='description')),
                ('competency_type', models.CharField(choices=[('TECHNICAL', 'Technical Skill'), ('BEHAVIORAL', 'Behavioral'), ('LEADERSHIP', 'Leadership'), ('COMMUNICATION', 'Communication'), ('CORE_VALUE', 'Core Value')], default='BEHAVIORAL', max_length=20, verbose_name='type')),
                ('level_1_description', models.TextField(blank=True, verbose_name='level 1 - developing')),
                ('level_2_description', models.TextField(blank=True, verbose_name='level 2 - competent')),
                ('level_3_description', models.TextField(blank=True, verbose_name='level 3 - proficient')),
                ('level_4_description', models.TextField(blank=True, verbose_name='level 4 - expert')),
                ('level_5_description', models.TextField(blank=True, verbose_name='level 5 - master')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='weight')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'competency',
                'verbose_name_plural': 'competencies',
                'ordering': ['framework', 'competency_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Q1 2024 Reviews, Annual 2024', max_length=200, verbose_name='cycle name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('review_type', models.CharField(choices=[('QUARTERLY', 'Quarterly Review'), ('MID_YEAR', 'Mid-Year Review'), ('ANNUAL', 'Annual Review'), ('PROBATION', 'Probation Review'), ('SPECIAL', 'Special Review')], default='QUARTERLY', max_length=20, verbose_name='review type')),
                ('start_date', models.DateField(verbose_name='cycle start date')),
                ('end_date', models.DateField(verbose_name='cycle end date')),
                ('review_period_start', models.DateField(help_text='Period being reviewed', verbose_name='review period start')),
                ('review_period_end', models.DateField(help_text='Period being reviewed', verbose_name='review period end')),
                ('deadline', models.DateField(help_text='Deadline for completing reviews', verbose_name='review deadline')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('auto_assign_reviewers', models.BooleanField(default=True, help_text='Automatically assign direct managers as reviewers', verbose_name='auto-assign reviewers')),
                ('send_reminders', models.BooleanField(default=True, help_text='Send reminder emails to reviewers', verbose_name='send reminders')),
                ('reminder_days_before', models.PositiveIntegerField(default=7, help_text='Send reminders this many days before deadline', verbose_name='reminder days before deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_created_review_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'performance review cycle',
                'verbose_name_plural': 'performance review cycles',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='performancetemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='performancefeedback',
            name='provided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_provided_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='perf_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'EMPLOYER_SUPERUSER', 'EMPLOYER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_conducted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewCycleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='reminder sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performance.performancereviewcycle')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='perf_review_assignments', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(blank=True, help_text='Created review for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_assignment', to='performance.performancereview')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Assigned reviewer for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'review cycle assignment',
                'verbose_name_plural': 'review cycle assignments',
                'ordering': ['cycle', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddField(
            model_name='performancereviewcycle',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template to use for reviews in this cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='performance.performancetemplate'),
        ),
        migrations.AddField(
            model_name='performancereviewcycle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', verbose_name='rating')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('evidence', models.TextField(blank=True, verbose_name='evidence/examples')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.competency')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='performance.performancereview')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'competency rating',
                'verbose_name_plural': 'competency ratings',
                'ordering': ['review', 'competency'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='framework name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default framework')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_created_competency_frameworks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'competency framework',
                'verbose_name_plural': 'competency frameworks',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='competency',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='performance.competencyframework'),
        ),
        migrations.AddField(
            model_name='competency',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
    ]
