# Generated by Django 4.2.28 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_competency_performancereviewcycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='challenges_faced',
            field=models.TextField(blank=True, verbose_name='challenges faced'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee_comments',
            field=models.TextField(blank=True, verbose_name='employee comments'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='employee submitted at'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='recommended_actions',
            field=models.TextField(blank=True, verbose_name='recommended actions'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer_comments',
            field=models.TextField(blank=True, verbose_name='reviewer comments'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewer completed at'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='self_rating',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'Outstanding'), ('EXCEEDS_EXPECTATIONS', 'Exceeds Expectations'), ('MEETS_EXPECTATIONS', 'Meets Expectations'), ('BELOW_EXPECTATIONS', 'Below Expectations'), ('UNSATISFACTORY', 'Unsatisfactory')], max_length=25, null=True, verbose_name='self rating'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='training_needs',
            field=models.TextField(blank=True, verbose_name='training needs'),
        ),
    ]
