# Generated by Django 4.2.28 on 2026-02-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_performancereview_challenges_faced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Review cycle this review belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='performance.performancereviewcycle'),
        ),
    ]
