version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 ems_project.wsgi:application"
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=209.38.225.139,localhost,127.0.0.1
      - SECRET_KEY=q6xKzf2C_IrJuTRNc-OiY6ZXyKdLzEJY-CmBBOxRnQnA_RSfV-dXk1mwY3dNySVBGbw
      - DATABASE_URL=sqlite:///db.sqlite3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
