# Generated by Django 4.2.24 on 2025-09-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'document category',
                'verbose_name_plural': 'document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('CERTIFICATE', 'Certificate'), ('ID', 'Identification Document'), ('LICENSE', 'Professional License'), ('MEDICAL', 'Medical Record'), ('TRAINING', 'Training Record'), ('PERFORMANCE', 'Performance Review'), ('POLICY', 'Company Policy'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='document title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='employee_documents/', verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes', verbose_name='file size')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='confidential')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'EMPLOYER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee document',
                'verbose_name_plural': 'employee documents',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('template_file', models.FileField(upload_to='document_templates/', verbose_name='template file')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documentcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20, verbose_name='access type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='accessed at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.employeedocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document access log',
                'verbose_name_plural': 'document access logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
