# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_documentcategory_default_document_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='category name'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeedocument',
            unique_together={('tenant', 'employee', 'title', 'version')},
        ),
    ]
