# Generated by Django 5.1.5 on 2026-03-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attendance', models.BooleanField(default=True, verbose_name='attendance emails')),
                ('email_leave', models.BooleanField(default=True, verbose_name='leave emails')),
                ('email_document', models.BooleanField(default=True, verbose_name='document emails')),
                ('email_performance', models.BooleanField(default=True, verbose_name='performance emails')),
                ('email_payroll', models.BooleanField(default=True, verbose_name='payroll emails')),
                ('email_training', models.BooleanField(default=True, verbose_name='training emails')),
                ('inapp_attendance', models.BooleanField(default=True, verbose_name='attendance notifications')),
                ('inapp_leave', models.BooleanField(default=True, verbose_name='leave notifications')),
                ('inapp_document', models.BooleanField(default=True, verbose_name='document notifications')),
                ('inapp_performance', models.BooleanField(default=True, verbose_name='performance notifications')),
                ('inapp_payroll', models.BooleanField(default=True, verbose_name='payroll notifications')),
                ('inapp_training', models.BooleanField(default=True, verbose_name='training notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('REMINDER', 'Reminder')], default='INFO', max_length=20, verbose_name='type')),
                ('category', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('DOCUMENT', 'Document'), ('PERFORMANCE', 'Performance'), ('PAYROLL', 'Payroll'), ('TRAINING', 'Training'), ('ONBOARDING', 'Onboarding'), ('ASSET', 'Asset'), ('PROJECT', 'Project'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='category')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
