# Generated by Django 4.2.24 on 2026-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_tenant_notificationpreference_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('DOCUMENT', 'Document'), ('PERFORMANCE', 'Performance'), ('PAYROLL', 'Payroll'), ('TRAINING', 'Training'), ('ONBOARDING', 'Onboarding'), ('ASSET', 'Asset'), ('PROJECT', 'Project'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='category'),
        ),
    ]
