# Generated by Django 4.2.24 on 2025-10-05 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'asset category',
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop Computer'), ('PHONE', 'Mobile Phone'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('PRINTER', 'Printer'), ('VEHICLE', 'Vehicle'), ('ACCESS_CARD', 'Access Card'), ('UNIFORM', 'Uniform'), ('TOOLS', 'Tools'), ('SOFTWARE', 'Software License'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='asset type')),
                ('asset_tag', models.CharField(help_text='Unique asset identifier', max_length=100, unique=True, verbose_name='asset tag')),
                ('name', models.CharField(max_length=200, verbose_name='asset name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='serial number')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase price')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='warranty expiry')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AVAILABLE', 'Available'), ('IN_REPAIR', 'In Repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=20, verbose_name='condition')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='assigned date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='return date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'EMPLOYER_SUPERUSER', 'EMPLOYER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='blu_assets.assetcategory')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee asset',
                'verbose_name_plural': 'employee assets',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('REPAIR', 'Repair'), ('UPGRADE', 'Upgrade'), ('CLEANING', 'Cleaning'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='REPAIR', max_length=20, verbose_name='maintenance type')),
                ('description', models.TextField(verbose_name='description')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='performed by')),
                ('performed_date', models.DateField(verbose_name='performed date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='blu_assets.employeeasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset maintenance log',
                'verbose_name_plural': 'asset maintenance logs',
                'ordering': ['-performed_date'],
            },
        ),
    ]
