# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        ('blu_assets', '0002_employeeasset_custodian_employeeasset_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='assetmaintenancelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='asset_tag',
            field=models.CharField(help_text='Unique asset identifier', max_length=100, verbose_name='asset tag'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeasset',
            unique_together={('tenant', 'asset_tag')},
        ),
    ]
