# Generated by Django 6.0.2 on 2026-02-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blu_assets', '0006_add_approval_workflow_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeasset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assetcollectionrecord',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetcollectionrecord',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='assetcollectionrecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancelog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancelog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='hr_approved_by',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='manager_approved_by',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='supervisor_approved_by',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='employeeasset',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeasset',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='employeeasset',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='employeeasset',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeasset',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeasset',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='AssetCollectionRecord',
        ),
        migrations.DeleteModel(
            name='AssetMaintenanceLog',
        ),
        migrations.DeleteModel(
            name='AssetRequest',
        ),
        migrations.DeleteModel(
            name='EmployeeAsset',
        ),
    ]
