# Generated by Django 6.0.2 on 2026-02-18 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0055_alter_user_platform_role'),
        ('blu_assets', '0007_remove_employeeasset_category_and_more'),
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'asset category',
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop Computer'), ('PHONE', 'Mobile Phone'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('PRINTER', 'Printer'), ('VEHICLE', 'Vehicle'), ('ACCESS_CARD', 'Access Card'), ('UNIFORM', 'Uniform'), ('TOOLS', 'Tools'), ('SOFTWARE', 'Software License'), ('OTHER', 'Other')], max_length=20, verbose_name='asset type')),
                ('asset_name', models.CharField(max_length=200, verbose_name='asset name')),
                ('description', models.TextField(verbose_name='description/justification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('urgency_reason', models.TextField(blank=True, help_text='Explain why this is urgent', verbose_name='urgency reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20, verbose_name='status')),
                ('current_approval_level', models.CharField(choices=[('SUPERVISOR', 'Supervisor Review'), ('MANAGER', 'Department Manager'), ('HR', 'HR Review'), ('ADMIN', 'Admin/Procurement')], default='SUPERVISOR', help_text='Current stage in approval workflow', max_length=20, verbose_name='current approval level')),
                ('supervisor_approved', models.BooleanField(default=False, verbose_name='supervisor approved')),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='supervisor approval date')),
                ('manager_approved', models.BooleanField(default=False, verbose_name='manager approved')),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='manager approval date')),
                ('hr_approved', models.BooleanField(default=False, verbose_name='HR approved')),
                ('hr_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='HR approval date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='final approval date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='final approved by')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='accounts.companydepartment', verbose_name='department')),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_hr_approved', to=settings.AUTH_USER_MODEL, verbose_name='HR reviewer')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_manager_approved', to=settings.AUTH_USER_MODEL, verbose_name='department manager')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('supervisor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_supervisor_approved', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'asset request',
                'verbose_name_plural': 'asset requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Office, room, or physical location', max_length=200, verbose_name='location')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop Computer'), ('PHONE', 'Mobile Phone'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('PRINTER', 'Printer'), ('VEHICLE', 'Vehicle'), ('ACCESS_CARD', 'Access Card'), ('UNIFORM', 'Uniform'), ('TOOLS', 'Tools'), ('SOFTWARE', 'Software License'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='asset type')),
                ('asset_tag', models.CharField(help_text='Unique asset identifier', max_length=100, verbose_name='asset tag')),
                ('name', models.CharField(max_length=200, verbose_name='asset name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='serial number')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase price')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='warranty expiry')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AVAILABLE', 'Available'), ('IN_REPAIR', 'In Repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=20, verbose_name='condition')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='assigned date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='return date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units for this asset record', verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'EMPLOYER_SUPERUSER', 'EMPLOYER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='blu_assets.assetcategory')),
                ('custodian', models.ForeignKey(blank=True, help_text='Department manager/supervisor responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_assets', to=settings.AUTH_USER_MODEL, verbose_name='custodian')),
                ('department', models.ForeignKey(blank=True, help_text='Department that owns this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assets', to='accounts.companydepartment', verbose_name='department')),
                ('employee', models.ForeignKey(blank=True, help_text='Employee currently using this asset', limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'employee asset',
                'verbose_name_plural': 'employee assets',
                'ordering': ['-assigned_date', '-created_at'],
                'unique_together': {('tenant', 'asset_tag')},
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('REPAIR', 'Repair'), ('UPGRADE', 'Upgrade'), ('CLEANING', 'Cleaning'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='REPAIR', max_length=20, verbose_name='maintenance type')),
                ('description', models.TextField(verbose_name='description')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='performed by')),
                ('performed_date', models.DateField(verbose_name='performed date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='blu_assets.employeeasset')),
            ],
            options={
                'verbose_name': 'asset maintenance log',
                'verbose_name_plural': 'asset maintenance logs',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='employee name')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='position/department')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('signature_data', models.TextField(help_text='Base64-encoded signature image', verbose_name='signature data')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_collections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to='blu_assets.employeeasset')),
            ],
            options={
                'verbose_name': 'asset collection record',
                'verbose_name_plural': 'asset collection records',
                'ordering': ['-signed_at'],
            },
        ),
    ]
