# Generated by Django 4.2.24 on 2025-10-07 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_company_button_color_company_card_header_color_and_more'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeasset',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='Department manager/supervisor responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_assets', to=settings.AUTH_USER_MODEL, verbose_name='custodian'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department that owns this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assets', to='accounts.companydepartment', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='location',
            field=models.CharField(blank=True, help_text='Office, room, or physical location', max_length=200, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee currently using this asset', limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop Computer'), ('PHONE', 'Mobile Phone'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('PRINTER', 'Printer'), ('VEHICLE', 'Vehicle'), ('ACCESS_CARD', 'Access Card'), ('UNIFORM', 'Uniform'), ('TOOLS', 'Tools'), ('SOFTWARE', 'Software License'), ('OTHER', 'Other')], max_length=20, verbose_name='asset type')),
                ('asset_name', models.CharField(max_length=200, verbose_name='asset name')),
                ('description', models.TextField(verbose_name='description/justification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('urgency_reason', models.TextField(blank=True, help_text='Explain why this is urgent', verbose_name='urgency reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20, verbose_name='status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='approval date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='accounts.companydepartment', verbose_name='department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'asset request',
                'verbose_name_plural': 'asset requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
