# Generated by Django 4.2.24 on 2025-10-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('PAYE', 'PAYE (Income Tax)'), ('NAPSA', 'NAPSA (Social Security)'), ('NHIMA', 'NHIMA (Health Insurance)'), ('LATE', 'Late Deduction'), ('ABSENT', 'Absent Deduction'), ('LOAN', 'Loan Repayment'), ('ADVANCE', 'Salary Advance'), ('OTHER', 'Other Deduction')], max_length=20, verbose_name='deduction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_statutory', models.BooleanField(default=False, help_text='PAYE, NAPSA, NHIMA', verbose_name='statutory deduction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_deductions', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'payroll deduction',
                'verbose_name_plural': 'payroll deductions',
                'ordering': ['payroll', 'deduction_type'],
            },
        ),
    ]
