# Generated by Django 4.2.24 on 2025-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrolldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='gratuity'),
        ),
    ]
