# Generated by Django 4.2.24 on 2025-11-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_payroll_gratuity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeebenefit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='benefit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeebenefit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='payrolldeduction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(choices=[('HEALTH_INSURANCE', 'Health Insurance'), ('DENTAL_INSURANCE', 'Dental Insurance'), ('VISION_INSURANCE', 'Vision Insurance'), ('LIFE_INSURANCE', 'Life Insurance'), ('RETIREMENT_401K', '401(k) Retirement Plan'), ('PENSION', 'Pension Plan'), ('PAID_TIME_OFF', 'Paid Time Off'), ('SICK_LEAVE', 'Sick Leave'), ('STUDY_LEAVE', 'Study Leave'), ('PARENTAL_LEAVE', 'Parental Leave'), ('TRANSPORT', 'Transportation Allowance'), ('MEAL_VOUCHER', 'Meal Voucher'), ('GYM_MEMBERSHIP', 'Gym Membership'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='benefit type'),
        ),
        migrations.AlterUniqueTogether(
            name='benefit',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeebenefit',
            unique_together={('tenant', 'employee', 'benefit', 'enrollment_date')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('tenant', 'employee', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('tenant', 'employee')},
        ),
    ]
