# Generated by Django 4.2.28 on 2026-02-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        ('payroll', '0004_alter_employeebenefit_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='claimed amount')),
                ('description', models.TextField(blank=True, verbose_name='claim description')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='benefit_claims/', verbose_name='supporting file')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('hr_note', models.TextField(blank=True, verbose_name='HR note')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='payroll.benefit')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_claims', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='payroll.employeebenefit')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['EMPLOYER_ADMIN', 'ADMINISTRATOR', 'EMPLOYEE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_claims_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'benefit claim',
                'verbose_name_plural': 'benefit claims',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
