# Generated by Django 4.2.28 on 2026-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='napsa_label',
            field=models.CharField(default='NAPSA', help_text='e.g. NAPSA (Zambia), SSNIT (Ghana), NSSF (Kenya/Uganda), UIF (South Africa)', max_length=60, verbose_name='social-security deduction label'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='nhima_label',
            field=models.CharField(default='NHIMA', help_text='e.g. NHIMA (Zambia), NHIS (Ghana), NHIF (Kenya), GEMS (South Africa)', max_length=60, verbose_name='health-insurance deduction label'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='paye_label',
            field=models.CharField(default='PAYE', help_text='e.g. PAYE (Zambia), PAYE (Ghana), Income Tax (Kenya), IRP5 (South Africa)', max_length=60, verbose_name='income-tax deduction label'),
        ),
    ]
