# Generated by Django 4.2.24 on 2025-09-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('review_type', models.CharField(choices=[('QUARTERLY', 'Quarterly Review'), ('MID_YEAR', 'Mid-Year Review'), ('ANNUAL', 'Annual Review'), ('PROBATION', 'Probation Review'), ('SPECIAL', 'Special Review')], default='QUARTERLY', max_length=20, verbose_name='review type')),
                ('is_default', models.BooleanField(default=False, verbose_name='default template')),
                ('sections', models.JSONField(default=dict, help_text='JSON structure defining template sections and fields', verbose_name='template sections')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'performance template',
                'verbose_name_plural': 'performance templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('QUARTERLY', 'Quarterly Review'), ('MID_YEAR', 'Mid-Year Review'), ('ANNUAL', 'Annual Review'), ('PROBATION', 'Probation Review'), ('SPECIAL', 'Special Review')], default='QUARTERLY', max_length=20, verbose_name='review type')),
                ('review_period_start', models.DateField(verbose_name='review period start')),
                ('review_period_end', models.DateField(verbose_name='review period end')),
                ('review_date', models.DateField(default=django.utils.timezone.now, verbose_name='review date')),
                ('overall_rating', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('EXCEEDS_EXPECTATIONS', 'Exceeds Expectations'), ('MEETS_EXPECTATIONS', 'Meets Expectations'), ('BELOW_EXPECTATIONS', 'Below Expectations'), ('UNSATISFACTORY', 'Unsatisfactory')], default='MEETS_EXPECTATIONS', max_length=25, verbose_name='overall rating')),
                ('title', models.CharField(max_length=200, verbose_name='review title')),
                ('objectives', models.TextField(blank=True, verbose_name='review objectives')),
                ('achievements', models.TextField(blank=True, verbose_name='achievements')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='areas for improvement')),
                ('development_plan', models.TextField(blank=True, verbose_name='development plan')),
                ('goals_next_period', models.TextField(blank=True, verbose_name='goals for next period')),
                ('additional_comments', models.TextField(blank=True, verbose_name='additional comments')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20, verbose_name='status')),
                ('is_confidential', models.BooleanField(default=True, verbose_name='confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'EMPLOYER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'performance review',
                'verbose_name_plural': 'performance reviews',
                'ordering': ['-review_date', '-created_at'],
                'unique_together': {('employee', 'review_type', 'review_period_start', 'review_period_end')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='metric name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metric_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('PERCENTAGE', 'Percentage'), ('CURRENCY', 'Currency'), ('TIME', 'Time-based')], default='NUMERIC', max_length=20, verbose_name='metric type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='target value')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='actual value')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='unit')),
                ('weight', models.PositiveIntegerField(default=100, help_text='Relative weight of this metric in the overall review', verbose_name='weight')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='achieved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'performance metric',
                'verbose_name_plural': 'performance metrics',
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='goal title')),
                ('description', models.TextField(blank=True, verbose_name='goal description')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress from 0 to 100%', verbose_name='progress percentage')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='target completion date')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='actual completion date')),
                ('success_criteria', models.TextField(blank=True, verbose_name='success criteria')),
                ('challenges', models.TextField(blank=True, verbose_name='challenges faced')),
                ('support_needed', models.TextField(blank=True, verbose_name='support needed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'performance goal',
                'verbose_name_plural': 'performance goals',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('SELF', 'Self Assessment'), ('MANAGER', 'Manager Feedback'), ('PEER', 'Peer Feedback'), ('SUBORDINATE', 'Subordinate Feedback'), ('CUSTOMER', 'Customer Feedback')], default='MANAGER', max_length=20, verbose_name='feedback type')),
                ('relationship_to_employee', models.CharField(blank=True, help_text='e.g., Direct Manager, Colleague, Team Member', max_length=100, verbose_name='relationship to employee')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', verbose_name='rating')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='areas for improvement')),
                ('overall_comments', models.TextField(blank=True, verbose_name='overall comments')),
                ('suggestions', models.TextField(blank=True, verbose_name='suggestions')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonymous')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_feedback', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'performance feedback',
                'verbose_name_plural': 'performance feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
