# Generated by Django 4.2.24 on 2025-09-26 18:27
# Modified to merge SuperAdmin into User model

from django.db import migrations, transaction
from django.utils import timezone


def merge_superadmin_to_user(apps, schema_editor):
    """Migrate SuperAdmin data to User model with SUPERADMIN role"""
    SuperAdmin = apps.get_model('accounts', 'SuperAdmin')
    User = apps.get_model('accounts', 'User')

    with transaction.atomic():
        # Get all SuperAdmin users
        superadmins = SuperAdmin.objects.all()

        for superadmin in superadmins:
            # Check if a user with this email already exists
            existing_user = User.objects.filter(email=superadmin.email).first()

            if existing_user:
                # Update existing user to be SUPERADMIN
                existing_user.role = 'SUPERADMIN'
                existing_user.first_name = superadmin.first_name or ''
                existing_user.last_name = superadmin.last_name or ''
                existing_user.phone_number = superadmin.phone_number or ''
                existing_user.is_active = superadmin.is_active
                existing_user.is_verified = superadmin.is_verified
                existing_user.must_change_password = superadmin.must_change_password
                existing_user.password_changed_at = superadmin.password_changed_at
                existing_user.created_at = superadmin.created_at
                existing_user.updated_at = superadmin.updated_at
                existing_user.last_login = superadmin.last_login
                existing_user.company = None  # SuperAdmins don't have companies
                existing_user.save()
            else:
                # Create new User with SUPERADMIN role
                User.objects.create(
                    email=superadmin.email,
                    first_name=superadmin.first_name or '',
                    last_name=superadmin.last_name or '',
                    phone_number=superadmin.phone_number or '',
                    role='SUPERADMIN',
                    is_active=superadmin.is_active,
                    is_verified=superadmin.is_verified,
                    must_change_password=superadmin.must_change_password,
                    password_changed_at=superadmin.password_changed_at,
                    created_at=superadmin.created_at,
                    updated_at=superadmin.updated_at,
                    last_login=superadmin.last_login,
                    company=None,  # SuperAdmins don't have companies
                    password=superadmin.password,  # Copy the hashed password
                )


def reverse_merge(apps, schema_editor):
    """Reverse migration - create SuperAdmin records from User SUPERADMIN records"""
    User = apps.get_model('accounts', 'User')
    SuperAdmin = apps.get_model('accounts', 'SuperAdmin')

    with transaction.atomic():
        # Get all SUPERADMIN users
        superadmin_users = User.objects.filter(role='SUPERADMIN')

        for user in superadmin_users:
            # Check if SuperAdmin already exists
            existing_superadmin = SuperAdmin.objects.filter(email=user.email).first()

            if not existing_superadmin:
                SuperAdmin.objects.create(
                    email=user.email,
                    first_name=user.first_name,
                    last_name=user.last_name,
                    phone_number=user.phone_number,
                    is_active=user.is_active,
                    is_verified=user.is_verified,
                    must_change_password=user.must_change_password,
                    password_changed_at=user.password_changed_at,
                    created_at=user.created_at,
                    updated_at=user.updated_at,
                    last_login=user.last_login,
                    password=user.password,  # Copy the hashed password
                )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_models'),
        ('accounts', '0011_alter_superadmin_date_joined_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_superadmin_to_user, reverse_merge),
        # Remove the SuperAdmin table after migration
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
