# Generated by Django 4.2.24 on 2025-09-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_companydepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_sender_name', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBiometricSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('sync_interval', models.PositiveIntegerField(default=15)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_settings', to='accounts.company')),
            ],
        ),
    ]
