# Generated by Cascade on 2025-09-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_token_companybiometricsettings_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_role',
            field=models.CharField(
                choices=[
                    ('EMPLOYEE', 'Employee'),
                    ('SUPERVISOR', 'Supervisor'),
                    ('HR', 'Hr'),
                    ('ACCOUNTANT', 'Accountant'),
                    ('ACCOUNTS', 'Accounts'),
                ],
                default='EMPLOYEE',
                max_length=20,
            ),
        ),
    ]
