# Generated by Django 4.2.24 on 2025-10-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_employeeprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='currency',
            field=models.CharField(blank=True, choices=[('ZMW', 'ZMW (Zambian Kwacha)'), ('USD', 'USD (US Dollar)')], default='ZMW', max_length=3),
        ),
    ]
