# Generated by Django 4.2.24 on 2025-10-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_employment_type_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range_past', models.PositiveIntegerField(default=2, help_text='Number of past years to show in year dropdown')),
                ('year_range_future', models.PositiveIntegerField(default=2, help_text='Number of future years to show in year dropdown')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Attendance Settings',
                'verbose_name_plural': 'Company Attendance Settings',
            },
        ),
    ]
