# Generated by Django 4.2.24 on 2025-10-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_companyattendancesettings_expected_work_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_leave_requests', models.BooleanField(default=True, help_text='Notify managers of leave requests')),
                ('email_leave_approvals', models.BooleanField(default=True, help_text='Notify employees of leave approvals/rejections')),
                ('email_document_uploads', models.BooleanField(default=True, help_text='Notify on document uploads')),
                ('email_performance_reminders', models.BooleanField(default=False, help_text='Send performance review reminders')),
                ('email_training_assignments', models.BooleanField(default=False, help_text='Notify on training assignments')),
                ('inapp_realtime', models.BooleanField(default=True, help_text='Real-time in-app notifications')),
                ('inapp_sound_alerts', models.BooleanField(default=True, help_text='Play sound for notifications')),
                ('inapp_desktop_notifications', models.BooleanField(default=False, help_text='Browser desktop notifications')),
                ('digest_time', models.TimeField(default='09:00:00', help_text='Time to send daily digest emails')),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest')], default='DAILY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Notification Settings',
                'verbose_name_plural': 'Company Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name/description for this key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for receiving events')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed API scopes/permissions')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company API Key',
                'verbose_name_plural': 'Company API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('SLACK', 'Slack'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('PAYROLL', 'Payroll API'), ('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('SMS', 'SMS Gateway')], max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Integration',
                'verbose_name_plural': 'Company Integrations',
                'unique_together': {('company', 'integration_type')},
            },
        ),
    ]
