# Generated by Django 4.2.24 on 2025-10-07 13:11

from django.db import migrations, models
from django.utils import timezone


def generate_company_ids(apps, schema_editor):
    """Generate company IDs for existing companies"""
    Company = apps.get_model('accounts', 'Company')
    
    for company in Company.objects.all():
        if not company.company_id:
            # Use company creation date if available, otherwise use today
            if hasattr(company, 'created_at') and company.created_at:
                timestamp = company.created_at.strftime('%Y%m%d')
            else:
                timestamp = timezone.now().strftime('%Y%m%d')
            
            # Count companies created on the same date
            counter = Company.objects.filter(
                created_at__date=company.created_at.date() if hasattr(company, 'created_at') and company.created_at else timezone.now().date()
            ).filter(id__lte=company.id).count()
            
            company.company_id = f"COMP-{timestamp}-{counter:03d}"
            company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_company_branding_fields'),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, null=True, help_text='Auto-generated company ID (e.g., COMP-20251007-001)', max_length=20),
        ),
        # Then populate existing companies
        migrations.RunPython(generate_company_ids, reverse_code=migrations.RunPython.noop),
        # Finally make it unique
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, help_text='Auto-generated company ID (e.g., COMP-20251007-001)', max_length=20, unique=True),
        ),
    ]
