# Generated by Django 4.2.24 on 2025-10-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_company_business_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='button_color',
            field=models.CharField(default='#3b82f6', help_text='Primary button color', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='card_header_color',
            field=models.CharField(default='#10b981', help_text='Content card header color', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='Top bar & sidebar color', max_length=7),
        ),
    ]
