# Generated by Django 5.1.5 on 2026-03-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapikey',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_settings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Branch Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='connected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companynotificationsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companynotificationsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companypaygrade',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_grades', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companypaygrade',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='accounts.companydepartment'),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_company', to='accounts.companyregistrationrequest'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeidconfiguration',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_config', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='employeeidconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.companybranch'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Direct supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.companybranch'),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_departments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Department Head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='accounts.enhanceddepartment'),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_connections', to='accounts.integration'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='company_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.companyintegration'),
        ),
        migrations.AddField(
            model_name='payrolldeductionsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deduction_settings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='systemsettingsaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsettingsaudit',
            name='system_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='accounts.systemsettings'),
        ),
        migrations.AlterUniqueTogether(
            name='companybranch',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companydepartment',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companyholiday',
            unique_together={('tenant', 'company', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='companypaygrade',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companyposition',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='enhanceddepartment',
            unique_together={('company', 'branch', 'name'), ('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='companyintegration',
            unique_together={('company', 'integration')},
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['-created_at'], name='accounts_in_created_48ea5b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['company_integration', '-created_at'], name='accounts_in_company_b18feb_idx'),
        ),
    ]
