# Generated by Django 5.1.5 on 2026-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_complete',
            field=models.BooleanField(default=True, help_text='False for newly approved companies until QSG is completed'),
        ),
    ]
