# Generated by Django 5.1.5 on 2026-03-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stamp_rotation',
            field=models.IntegerField(default=0, help_text='Stamp rotation angle in degrees (0-360)'),
        ),
    ]
