# Generated by Django 5.1.5 on 2025-01-23 20:00

import secrets
import string
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_options_company_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_position', models.CharField(blank=True, max_length=100)),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PREMIUM', 'Premium Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', max_length=20)),
                ('number_of_employees', models.PositiveIntegerField(default=1)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='accounts.user')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('generated_password', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Company Registration Request',
                'verbose_name_plural': 'Company Registration Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_employees',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_company', to='accounts.companyregistrationrequest'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PREMIUM', 'Premium Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
