# Generated by Django 4.2.24 on 2025-09-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMINISTRATOR', 'Administrator'), ('EMPLOYER_ADMIN', 'Employer Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
