# Generated by Django 4.2.24 on 2025-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_companyemailsettings_companybiometricsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybiometricsettings',
            old_name='token',
            new_name='api_key',
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='device_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
