# Generated by Django 4.2.24 on 2025-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employeeprofile_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUPERVISOR', 'Supervisor'), ('HR', 'HR'), ('ACCOUNTANT', 'Accountant'), ('ACCOUNTS', 'Accounts')], default='EMPLOYEE', max_length=20),
        ),
    ]
