# Generated by Django 4.2.24 on 2025-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_currency_to_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Contract end date', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Contract start date', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Probation period end date', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_start_date',
            field=models.DateField(blank=True, help_text='Probation period start date', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='temporary_end_date',
            field=models.DateField(blank=True, help_text='Temporary employment end date', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='temporary_start_date',
            field=models.DateField(blank=True, help_text='Temporary employment start date', null=True),
        ),
    ]
