# Generated by Django 4.2.24 on 2025-10-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_companyattendancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancesettings',
            name='expected_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Expected work hours per day', max_digits=4),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Grace period in minutes before marking as late'),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='overtime_threshold',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours threshold for overtime', max_digits=4),
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name (e.g., Christmas Day, New Year)', max_length=200)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='Recurring annually on same date')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Holiday',
                'verbose_name_plural': 'Company Holidays',
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
