# Generated by Django 4.2.24 on 2025-10-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_companybranch_employeeprofile_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye_tax_brackets', models.JSONField(default=list, help_text='Tax brackets with min, max, and rate percentage')),
                ('paye_enabled', models.BooleanField(default=True)),
                ('napsa_employee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Employee contribution percentage', max_digits=5)),
                ('napsa_employer_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Employer contribution percentage', max_digits=5)),
                ('napsa_enabled', models.BooleanField(default=True)),
                ('nhima_employee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly amount deducted from employee', max_digits=10)),
                ('nhima_employer_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly amount paid by employer', max_digits=10)),
                ('nhima_enabled', models.BooleanField(default=True)),
                ('late_deduction_per_occurrence', models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted per late occurrence', max_digits=10)),
                ('absent_deduction_per_day', models.DecimalField(decimal_places=2, default=0, help_text="Amount deducted per absent day (or full day's pay)", max_digits=10)),
                ('absent_deduction_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('DAILY_RATE', 'Daily Rate (Salary/Working Days)')], default='DAILY_RATE', max_length=20)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deduction_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Payroll Deduction Settings',
                'verbose_name_plural': 'Payroll Deduction Settings',
            },
        ),
    ]
