# Generated by Django 4.2.24 on 2025-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_update_payroll_settings_to_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldeductionsettings',
            name='gratuity_eligibility_months',
            field=models.IntegerField(default=12, help_text='Minimum months of service required for gratuity eligibility'),
        ),
        migrations.AddField(
            model_name='payrolldeductionsettings',
            name='gratuity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrolldeductionsettings',
            name='gratuity_percentage',
            field=models.DecimalField(decimal_places=2, default=8.33, help_text='Percentage of basic salary accrued monthly (8.33% = 1 month salary per year)', max_digits=5),
        ),
    ]
