# Generated by Django 4.2.24 on 2025-10-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_payrolldeductionsettings_gratuity_eligibility_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_stamp',
            field=models.ImageField(blank=True, help_text='Company official stamp for payslips', null=True, upload_to='company_stamps/'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Zambia', max_length=100),
        ),
    ]
