# Generated by Django 4.2.24 on 2025-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_company_city_company_company_stamp_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#10b981', help_text='Secondary/accent color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, help_text='Authorized signatory signature', null=True, upload_to='company_signatures/'),
        ),
        migrations.AddField(
            model_name='company',
            name='text_color',
            field=models.CharField(default='#1e293b', help_text='Primary text color (hex)', max_length=7),
        ),
    ]
