# Generated by Django 4.2.24 on 2025-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_add_company_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_registration',
            field=models.FileField(blank=True, help_text='PACRA Certificate', null=True, upload_to='company_documents/registration/'),
        ),
        migrations.AddField(
            model_name='company',
            name='napsa_certificate',
            field=models.FileField(blank=True, help_text='NAPSA Certificate', null=True, upload_to='company_documents/napsa/'),
        ),
        migrations.AddField(
            model_name='company',
            name='nhima_certificate',
            field=models.FileField(blank=True, help_text='NHIMA Certificate', null=True, upload_to='company_documents/nhima/'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_accent_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_footer_text',
            field=models.TextField(blank=True, default='This is a computer-generated payslip and does not require a signature.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_header_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_header_style',
            field=models.CharField(choices=[('logo_left', 'Logo Left'), ('logo_center', 'Logo Center'), ('logo_right', 'Logo Right'), ('full_width', 'Full Width')], default='logo_left', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_layout',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('detailed', 'Detailed'), ('compact', 'Compact')], default='modern', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='show_company_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_company_stamp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_confidentiality_notice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_qr_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_tax_breakdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_ytd_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='TPIN Certificate', null=True, upload_to='company_documents/tax/'),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_license',
            field=models.FileField(blank=True, help_text='Trading License', null=True, upload_to='company_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='company',
            name='workers_compensation',
            field=models.FileField(blank=True, help_text='Workers Compensation Certificate', null=True, upload_to='company_documents/wcf/'),
        ),
    ]
