# Generated by Django 4.2.24 on 2025-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_company_button_color_company_card_header_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Top bar & sidebar color', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#6b7280', help_text='Secondary/accent color (hex)', max_length=7),
        ),
    ]
