# Generated by Django 4.2.24 on 2025-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_company_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#2d3748', help_text='Top bar & sidebar color', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#718096', help_text='Secondary/accent color (hex)', max_length=7),
        ),
    ]
