# Generated by Django 4.2.24 on 2025-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_company_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payslip_address_position',
            field=models.CharField(default='top-right', help_text='Company address position', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_field_positions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field positions for drag-and-drop'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_footer_content',
            field=models.TextField(blank=True, help_text='Custom footer HTML/text'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_header_content',
            field=models.TextField(blank=True, help_text='Custom header HTML/text'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_logo_position',
            field=models.CharField(default='top-left', help_text='Logo position (e.g., top-left, top-center)', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_section_order',
            field=models.JSONField(blank=True, default=list, help_text='Order of sections: employee_info, salary_info, deductions, etc.'),
        ),
        migrations.AddField(
            model_name='company',
            name='payslip_stamp_position',
            field=models.CharField(default='bottom-right', help_text='Stamp position', max_length=50),
        ),
    ]
