# Generated by Django 4.2.24 on 2025-10-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_company_payslip_address_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payslip_section_color',
            field=models.CharField(blank=True, default='#C5D9F1', help_text='Color for section headers (Earnings, Deductions, etc.)', max_length=7),
        ),
    ]
