# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        ('accounts', '0038_company_payslip_section_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyapikey',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companybiometricsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companynotificationsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companypaygrade',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeidconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='enhanceddepartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='companyholiday',
            unique_together={('tenant', 'company', 'date')},
        ),
    ]
