# Generated by Django 4.2.24 on 2025-11-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_companyholiday_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='integration name')),
                ('integration_type', models.CharField(choices=[('SLACK', 'Slack'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('PAYROLL_API', 'Payroll System'), ('SMS_GATEWAY', 'SMS Gateway'), ('EMAIL_SERVICE', 'Email Service'), ('HR_SYSTEM', 'HR System'), ('ACCOUNTING', 'Accounting System'), ('OTHER', 'Other')], max_length=30, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon_emoji', models.CharField(blank=True, max_length=10, verbose_name='icon emoji')),
                ('requires_oauth', models.BooleanField(default=True, verbose_name='requires OAuth')),
                ('oauth_authorize_url', models.URLField(blank=True, verbose_name='OAuth authorize URL')),
                ('oauth_token_url', models.URLField(blank=True, verbose_name='OAuth token URL')),
                ('oauth_scope', models.TextField(blank=True, help_text='Space-separated scopes', verbose_name='OAuth scope')),
                ('api_base_url', models.URLField(blank=True, verbose_name='API base URL')),
                ('documentation_url', models.URLField(blank=True, verbose_name='documentation URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'integration',
                'verbose_name_plural': 'integrations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='companyintegration',
            options={'ordering': ['-created_at'], 'verbose_name': 'company integration', 'verbose_name_plural': 'company integrations'},
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='configuration'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='connected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='error count'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='last error'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('PENDING', 'Pending Authorization')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='token expires at'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='webhook secret'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='access_token',
            field=models.TextField(blank=True, verbose_name='access token'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='connected at'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='refresh_token',
            field=models.TextField(blank=True, verbose_name='refresh token'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='webhook URL'),
        ),
        migrations.AlterUniqueTogether(
            name='companyintegration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_connections', to='accounts.integration'),
        ),
        migrations.AlterUniqueTogether(
            name='companyintegration',
            unique_together={('company', 'integration')},
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('SYNC', 'Data Sync'), ('WEBHOOK', 'Webhook Received'), ('ERROR', 'Error'), ('TOKEN_REFRESH', 'Token Refreshed')], max_length=30, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='request data')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='response data')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.companyintegration')),
            ],
            options={
                'verbose_name': 'integration log',
                'verbose_name_plural': 'integration logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_in_created_48ea5b_idx'), models.Index(fields=['company_integration', '-created_at'], name='accounts_in_company_b18feb_idx')],
            },
        ),
        migrations.RemoveField(
            model_name='companyintegration',
            name='config_data',
        ),
        migrations.RemoveField(
            model_name='companyintegration',
            name='integration_type',
        ),
        migrations.RemoveField(
            model_name='companyintegration',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='companyintegration',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='companyintegration',
            name='tenant',
        ),
    ]
