# Generated by Django 4.2.24 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_integration_alter_companyintegration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_public_company_registration', models.BooleanField(default=True, help_text='Allow companies to submit registration requests via the public registration form.')),
                ('default_subscription_plan', models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PREMIUM', 'Premium Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', help_text='Default subscription plan suggested during company registration.', max_length=20)),
                ('registration_admin_email', models.EmailField(blank=True, help_text='Override notification email for new company registrations. Leave blank to use ADMIN_EMAIL.', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If enabled, the system can display maintenance notices (not yet enforced everywhere).')),
                ('maintenance_message', models.TextField(blank=True, default='The system is currently under maintenance. Please try again later.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
