# Generated by Django 4.2.24 on 2025-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='country',
            field=models.CharField(default='Zambia', max_length=100),
        ),
    ]
