# Generated by Django 4.2.24 on 2025-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_companyregistrationrequest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='billing_preference',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('MONTHLY', 'Monthly subscription'), ('YEARLY', 'Yearly subscription')], default='TRIAL', max_length=20),
        ),
    ]
