# Generated by Django 4.2.24 on 2025-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_companyregistrationrequest_billing_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('SUPPORT', 'Support'), ('REGISTRATION', 'Registration'), ('BILLING', 'Billing')], help_text='Platform-level staff role for the technical owner portal.', max_length=20, null=True),
        ),
    ]
