# Generated by Django 4.2.24 on 2025-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_user_platform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Admin'), ('SUPPORT', 'Support'), ('REGISTRATION', 'Registration'), ('BILLING', 'Billing')], help_text='Platform-level staff role for the technical owner portal.', max_length=20, null=True),
        ),
    ]
