# Generated by Django 4.2.24 on 2025-11-25 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_user_platform_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_analytics_module',
            field=models.BooleanField(default=True, help_text='Enable the System Owner analytics dashboard.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_billing_module',
            field=models.BooleanField(default=True, help_text='Enable the System Owner billing overview module.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_support_module',
            field=models.BooleanField(default=True, help_text='Enable the System Owner support center module.'),
        ),
        migrations.CreateModel(
            name='SystemSettingsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_changes', to=settings.AUTH_USER_MODEL)),
                ('system_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='accounts.systemsettings')),
            ],
            options={
                'verbose_name': 'System Settings Audit',
                'verbose_name_plural': 'System Settings Audits',
                'ordering': ['-changed_at'],
            },
        ),
    ]
