# Generated by Django 4.2.24 on 2025-12-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_employeeprofile_on_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Uploaded signature for e-forms.', null=True, upload_to='user_signatures/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='signature_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed PIN/password protecting signature use.', max_length=128),
        ),
    ]
