# Generated by Django 4.2.24 on 2026-02-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        ('accounts', '0048_employeeprofile_signature_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_attendance', models.BooleanField(default=True, help_text='Enable Attendance module')),
                ('enable_leave', models.BooleanField(default=True, help_text='Enable Leave Management module')),
                ('enable_payroll', models.BooleanField(default=True, help_text='Enable Payroll module')),
                ('enable_performance', models.BooleanField(default=True, help_text='Enable Performance Reviews module')),
                ('enable_training', models.BooleanField(default=True, help_text='Enable Training module')),
                ('enable_onboarding', models.BooleanField(default=True, help_text='Enable Onboarding module')),
                ('enable_assets', models.BooleanField(default=True, help_text='Enable Assets Management module')),
                ('enable_eforms', models.BooleanField(default=True, help_text='Enable E-Forms module')),
                ('enable_benefits', models.BooleanField(default=True, help_text='Enable Benefits module')),
                ('enable_documents', models.BooleanField(default=True, help_text='Enable Documents module')),
                ('enable_requests', models.BooleanField(default=True, help_text='Enable Employee Requests module')),
                ('enable_communication', models.BooleanField(default=True, help_text='Enable Communication module')),
                ('enable_reports', models.BooleanField(default=True, help_text='Enable Reports module')),
                ('enable_biometric_integration', models.BooleanField(default=False, help_text='Enable biometric device integration')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('enable_slack_integration', models.BooleanField(default=False, help_text='Enable Slack integration')),
                ('require_leave_approval', models.BooleanField(default=True, help_text='Require approval for leave requests')),
                ('require_document_approval', models.BooleanField(default=True, help_text='Require approval for documents')),
                ('require_request_approval', models.BooleanField(default=True, help_text='Require approval for employee requests')),
                ('allow_manual_attendance', models.BooleanField(default=True, help_text='Allow manual attendance entry')),
                ('require_attendance_photo', models.BooleanField(default=False, help_text='Require photo for attendance')),
                ('attendance_grace_period_minutes', models.IntegerField(default=15, help_text='Grace period for late arrivals (minutes)')),
                ('max_leave_days_per_year', models.IntegerField(default=30, help_text='Maximum leave days per year')),
                ('allow_negative_leave_balance', models.BooleanField(default=False, help_text='Allow negative leave balance')),
                ('payroll_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', help_text='Payroll processing frequency', max_length=20)),
                ('payroll_day_of_month', models.IntegerField(default=25, help_text='Day of month for payroll processing')),
                ('require_password_change_days', models.IntegerField(default=90, help_text='Days before password change required (0 = never)')),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('enable_two_factor_auth', models.BooleanField(default=False, help_text='Enable two-factor authentication')),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for documents and reports', null=True, upload_to='company_logos/')),
                ('company_stamp', models.ImageField(blank=True, help_text='Company stamp for official documents', null=True, upload_to='company_stamps/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
