# Generated by Django 4.2.24 on 2026-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alternative_phone',
            field=models.CharField(blank=True, help_text='Secondary contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], help_text='Approximate number of employees', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry or sector', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal / Zip code', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, help_text='Province or state', max_length=100),
        ),
    ]
