# Generated by Django 4.2.24 on 2026-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_add_company_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='security_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Security configuration: password_policy, session, twofa, login_restrictions'),
        ),
    ]
