# Generated by Django 4.2.24 on 2026-02-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_add_security_settings_to_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyintegration',
            table='accounts_companyintegration',
        ),
        migrations.AlterModelTable(
            name='integration',
            table='accounts_integration',
        ),
        migrations.AlterModelTable(
            name='integrationlog',
            table='accounts_integrationlog',
        ),
    ]
