# Generated by Django 4.2.24 on 2026-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_billinginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PROFESSIONAL', 'Professional Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyregistrationrequest',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PROFESSIONAL', 'Professional Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PROFESSIONAL', 'Professional Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='BASIC', help_text='Default subscription plan suggested during company registration.', max_length=20),
        ),
    ]
