# Generated by Django 6.0.2 on 2026-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_change_premium_to_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Admin'), ('SUPPORT', 'Support'), ('REGISTRATION', 'Registration'), ('BILLING', 'Billing'), ('ACCOUNT_MANAGER', 'Account Manager')], help_text='Platform-level staff role for the technical owner portal.', max_length=20, null=True),
        ),
    ]
