# Generated by Django 4.2.28 on 2026-02-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_user_platform_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_remote_attendance',
            field=models.BooleanField(default=False, help_text='Allow employees to clock in from anywhere (overrides geofencing)'),
        ),
        migrations.AddField(
            model_name='company',
            name='enforce_geofencing',
            field=models.BooleanField(default=False, help_text='Require employees to be within geofence radius to clock in/out'),
        ),
        migrations.AddField(
            model_name='company',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=100, help_text='Allowed radius in meters from office location for clock-in (default: 100m)'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office location latitude for GPS attendance verification', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office location longitude for GPS attendance verification', max_digits=9, null=True),
        ),
    ]
