# Generated by Django 4.2.28 on 2026-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_add_geofencing_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=100, help_text='Allowed radius in meters from branch location for clock-in (default: 100m)'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Branch location latitude for GPS attendance verification', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Branch location longitude for GPS attendance verification', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='require_gps_attendance',
            field=models.BooleanField(default=True, help_text="Require GPS tracking for this employee's attendance (can be disabled for remote workers)"),
        ),
    ]
