# Generated by Django 4.2.28 on 2026-02-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_add_branch_gps_and_employee_gps_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='office_location_name',
            field=models.CharField(blank=True, help_text="Office location name/address (e.g., '123 Main St, Lusaka, Zambia')", max_length=500),
        ),
    ]
