# Generated by Django 4.2.28 on 2026-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_add_office_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='require_renewal_approval',
            field=models.BooleanField(default=True, help_text='Require admin approval for contract renewals. Disable for direct renewal (SMEs)'),
        ),
    ]
