# Generated by Django 4.2.28 on 2026-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_company_require_renewal_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_attendance_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_document_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=False, help_text='Master switch for all email notifications'),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_leave_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_payroll_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_performance_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='enable_training_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='from_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyemailsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
