# Generated by Django 4.2.24 on 2025-10-19 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_company_alter_user_role_employeeprofile_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('plan_name', models.CharField(default='BASIC', max_length=50)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_employees', models.PositiveIntegerField(default=25)),
                ('max_projects', models.PositiveIntegerField(default=10)),
                ('storage_quota_gb', models.FloatField(default=5.0)),
                ('primary_color', models.CharField(default='#1F2A44', max_length=7)),
                ('secondary_color', models.CharField(default='#0099FF', max_length=7)),
                ('accent_color', models.CharField(default='#38BDF8', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='accounts.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant_management.tenant')),
            ],
            options={
                'ordering': ('-is_primary', 'domain'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('STAFF', 'Staff Member'), ('VIEWER', 'Viewer')], default='STAFF', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='tenant_management.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant User Role',
                'verbose_name_plural': 'Tenant User Roles',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
