# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
