"""
Django settings for ems_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# APPS_ROOT removed to prevent import conflicts - use full paths like blu_staff.apps.performance
# APPS_ROOT = BASE_DIR / 'blu_staff' / 'apps'
# if APPS_ROOT.exists():
#     sys.path.insert(0, str(APPS_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-hk#y))sfv81zpb*smz!ar3f*f_c2_x4$nh2^cnr(4i&6#v)x1u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_yasg',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    
    # BLU Suite core modules
    'tenant_management.apps.TenantManagementConfig',
    'blu_core',
    'blu_staff',
    'blu_assets.apps.BluAssetsConfig',  # Asset Management Suite (AMS) - Standalone
    'blu_staff.apps.assets_old_backup.apps.AssetsConfig',  # Legacy assets app (label "assets") for migration graph
    'blu_projects',
    'blu_analytics',
    'blu_billing',
    'blu_support',

    # EMS legacy apps (to be refactored under blu_staff)
    'blu_staff.apps.accounts.apps.AccountsConfig',
    'blu_staff.apps.attendance.apps.AttendanceConfig',
    'blu_staff.apps.documents.apps.DocumentsConfig',
    'blu_staff.apps.performance.apps.PerformanceConfig',
    'blu_staff.apps.payroll.apps.PayrollConfig',
    'blu_staff.apps.training.apps.TrainingConfig',
    'blu_staff.apps.onboarding.apps.OnboardingConfig',
    'blu_staff.apps.notifications.apps.NotificationsConfig',
    'blu_staff.apps.requests.apps.RequestsConfig',
    'blu_staff.apps.communication.apps.CommunicationConfig',
    'blu_staff.apps.eforms.apps.EformsConfig',
    'blu_staff.apps.contracts.apps.ContractsConfig',
    'ems_project.apps.EmsProjectConfig',
    'ems_project.payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenant_management.middleware.TenantContextMiddleware',
]

ROOT_URLCONF = 'ems_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ems_project.context_processors.user_role_context',
                'ems_project.context_processors.unread_counts',
                'ems_project.context_processors.company_settings_context',
                'ems_project.context_processors.system_settings_context',
                'ems_project.context_processors.currency_context',
                'tenant_management.context_processors.tenant_theme',
                'blu_projects.context_processors.pms_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ems_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Login URL for Django auth redirects
LOGIN_URL = '/login/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only for development
CORS_ALLOW_CREDENTIALS = True

# CSRF settings for development
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
# For development, allow CSRF cookie to be set
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token if needed
CSRF_COOKIE_SECURE = False  # Set to False for HTTP in development

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'emmanuelsimwanza2@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'YOUR_GMAIL_APP_PASSWORD_HERE')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@eiscomtech.com')

# Admin email for notifications
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'emmanuelsimwanza2@gmail.com')  # Your admin email

# Site URL for email links
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

TENANT_ROUTING_STRATEGY = os.getenv('TENANT_ROUTING_STRATEGY', 'path')
TENANT_PATH_PREFIX = os.getenv('TENANT_PATH_PREFIX', 'workspace')
TENANT_SESSION_KEY = 'active_tenant_id'
TENANT_EXCLUDED_PATH_PREFIXES = tuple(
    os.getenv('TENANT_EXCLUDED_PATHS', '/admin,/static,/media,/health').split(',')
)

# Stripe Payment Configuration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_51P9DxmAkon9QsgJlzX5kKqOlVRbp3Gq6SneGXilmMDBxUgLD8jzYjBpUS0ZO3NZStAmcR0M7SGkWGvTwISoo8kio00IMpkXdZA')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51P9DxmAkon9QsgJlKEQilSPrYPOjdKeLPIO2oQRQjFIPPqWpczk99pkvhlVNSqaY7NOPLEasWQKngK8cxSjvnXGT00h9Vqa7Kl')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_1234567890abcdef1234567890abcdef')

# Payment Plans Configuration
DEFAULT_CURRENCY = 'USD'
DEFAULT_PAYMENT_PLAN_PRICE = 29.99  # Default monthly price

# Payment Requirements
REQUIRE_PAYMENT_FOR_REGISTRATION = os.getenv('REQUIRE_PAYMENT_FOR_REGISTRATION', 'True').lower() == 'true'
