"""
Django settings for ems_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Python 3.14 creates longer implicit __context__ exception chains during Django
# template attribute lookups. Django 4.2's get_exception_info recurses on those
# chains and hits the default limit. Raise it here as a compatibility shim.
sys.setrecursionlimit(10000)

import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# APPS_ROOT removed to prevent import conflicts - use full paths like blu_staff.apps.performance
# APPS_ROOT = BASE_DIR / 'blu_staff' / 'apps'
# if APPS_ROOT.exists():
#     sys.path.insert(0, str(APPS_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default value - application will fail if SECRET_KEY not set (security best practice)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-CHANGE-IN-PRODUCTION' if os.getenv('DJANGO_ENV') == 'development' else None)
if not SECRET_KEY:
    raise ValueError('SECRET_KEY environment variable must be set in production')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for security - explicitly enable in development only
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_yasg',
    'axes',  # Account lockout protection
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    
    # BLU Suite core modules
    'tenant_management.apps.TenantManagementConfig',
    'blu_core.apps.BluCoreConfig',
    'blu_staff',
    'blu_assets.apps.BluAssetsConfig',  # Asset Management Suite (AMS) - Standalone
    'blu_staff.apps.assets_old_backup.apps.AssetsConfig',  # Legacy assets app (label "assets") for migration graph
    'blu_projects',
    'blu_analytics',
    'blu_billing',
    'blu_support',

    # EMS legacy apps (to be refactored under blu_staff)
    'blu_staff.apps.accounts.apps.AccountsConfig',
    'blu_staff.apps.attendance.apps.AttendanceConfig',
    'blu_staff.apps.documents.apps.DocumentsConfig',
    'blu_staff.apps.performance.apps.PerformanceConfig',
    'blu_staff.apps.payroll.apps.PayrollConfig',
    'blu_staff.apps.training.apps.TrainingConfig',
    'blu_staff.apps.onboarding.apps.OnboardingConfig',
    'blu_staff.apps.notifications.apps.NotificationsConfig',
    'blu_staff.apps.requests.apps.RequestsConfig',
    'blu_staff.apps.communication.apps.CommunicationConfig',
    'blu_staff.apps.eforms.apps.EformsConfig',
    'blu_staff.apps.contracts.apps.ContractsConfig',
    'ems_project.apps.EmsProjectConfig',
    'ems_project.payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Must be directly after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Account lockout - must be after AuthenticationMiddleware
    'tenant_management.middleware.TenantContextMiddleware',
]

ROOT_URLCONF = 'ems_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ems_project.context_processors.user_role_context',
                'ems_project.context_processors.unread_counts',
                'ems_project.context_processors.company_settings_context',
                'ems_project.context_processors.system_settings_context',
                'ems_project.context_processors.currency_context',
                'tenant_management.context_processors.tenant_theme',
                'blu_projects.context_processors.pms_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ems_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Increased from default 8
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'ems_project.validators.UppercaseValidator',
    },
    {
        'NAME': 'ems_project.validators.LowercaseValidator',
    },
    {
        'NAME': 'ems_project.validators.NumberValidator',
    },
    {
        'NAME': 'ems_project.validators.SpecialCharacterValidator',
    },
]

# Session Security Settings
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout (instead of 2 weeks default)
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict CSRF protection
SESSION_SAVE_EVERY_REQUEST = True  # Rotate session ID on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Clear session when browser closes

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
SECURE_REFERRER_POLICY = 'same-origin'  # Limit referrer information

# HTTPS/SSL Settings (applied when not in DEBUG mode)
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB max file size in memory
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB max request size
FILE_UPLOAD_PERMISSIONS = 0o644  # Secure file permissions
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Secure directory permissions

# Allowed file extensions for uploads (whitelist)
ALLOWED_UPLOAD_EXTENSIONS = [
    'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
    'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg',
    'txt', 'csv', 'zip', 'rar'
]

# Maximum file sizes by type (in bytes)
MAX_FILE_SIZE = {
    'image': 5242880,  # 5MB for images
    'document': 10485760,  # 10MB for documents
    'default': 10485760,  # 10MB default
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Login URL for Django auth redirects
LOGIN_URL = '/login/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS settings - SECURITY: Never allow all origins
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://127.0.0.1:8000,http://localhost:8000').split(',')

# CSRF settings - SECURITY: Secure by default
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1:8000,http://localhost:8000').split(',')
CSRF_COOKIE_SAMESITE = 'Lax'  # Allow same-site form submissions
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token for form submissions
CSRF_COOKIE_SECURE = not DEBUG  # Secure in production (HTTPS only)
CSRF_USE_SESSIONS = False  # Keep token in cookie for API compatibility

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
# SECURITY: No default credentials - must be set via environment variables
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@eiscomtech.com')

# Admin email for notifications
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'emmanuelsimwanza2@gmail.com')  # Your admin email

# Site URL for email links
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

TENANT_ROUTING_STRATEGY = os.getenv('TENANT_ROUTING_STRATEGY', 'path')
TENANT_PATH_PREFIX = os.getenv('TENANT_PATH_PREFIX', 'workspace')
TENANT_SESSION_KEY = 'active_tenant_id'
TENANT_EXCLUDED_PATH_PREFIXES = tuple(
    os.getenv('TENANT_EXCLUDED_PATHS', '/admin,/static,/media,/health').split(',')
)

# Payment Requirements
REQUIRE_PAYMENT_FOR_REGISTRATION = os.getenv('REQUIRE_PAYMENT_FOR_REGISTRATION', 'True').lower() == 'true'

# Stripe Payment Configuration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Validate Stripe keys are set if payment is required
if REQUIRE_PAYMENT_FOR_REGISTRATION and not all([STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY]):
    import warnings
    warnings.warn('Stripe API keys not configured but payment is required')

# Payment Plans Configuration
DEFAULT_CURRENCY = 'USD'
DEFAULT_PAYMENT_PLAN_PRICE = 29.99  # Default monthly price

# Django-Axes Configuration (Brute Force Protection)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes backend for login attempt tracking
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

# Axes Settings
AXES_FAILURE_LIMIT = 5  # Lock account after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Lock for 1 hour (in hours)
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True  # Lock by username + IP combination
AXES_RESET_ON_SUCCESS = True  # Reset failed attempts counter on successful login
AXES_LOCKOUT_TEMPLATE = None  # Use default lockout response
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]  # Track by username and IP
AXES_VERBOSE = True  # Enable verbose logging
AXES_ENABLE_ADMIN = True  # Enable admin interface for locked accounts
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False  # Don't extend lockout on additional attempts

# Logging Configuration for Security Events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
        'axes_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'axes.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['axes_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['security_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
