# Generated by Django 5.1.5 on 2026-03-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenant_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent Employment'), ('FIXED_TERM', 'Fixed-Term Contract'), ('PROBATION', 'Probationary Contract'), ('TEMPORARY', 'Temporary Contract'), ('CONSULTANT', 'Consultant Agreement'), ('PART_TIME', 'Part-Time Contract'), ('INTERNSHIP', 'Internship Agreement')], max_length=20)),
                ('template_content', models.TextField(help_text='Contract template with placeholders like {{employee_name}}, {{job_title}}, etc.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('default_probation_months', models.PositiveIntegerField(blank=True, null=True)),
                ('default_notice_period_days', models.PositiveIntegerField(default=30)),
                ('default_working_hours', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent Employment'), ('FIXED_TERM', 'Fixed-Term Contract'), ('PROBATION', 'Probationary Contract'), ('TEMPORARY', 'Temporary Contract'), ('CONSULTANT', 'Consultant Agreement'), ('PART_TIME', 'Part-Time Contract'), ('INTERNSHIP', 'Internship Agreement')], default='PERMANENT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PENDING_RENEWAL', 'Pending Renewal'), ('RENEWED', 'Renewed'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for permanent contracts', null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('renewal_notice_period_days', models.PositiveIntegerField(default=30, help_text='Days before expiry to send renewal notice')),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew contract')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('salary_frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('working_hours_per_week', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('probation_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/documents/')),
                ('signed_contract_document', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('special_clauses', models.TextField(blank=True, help_text='Any special terms or clauses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_notification_sent', models.BooleanField(default=False)),
                ('expiry_notification_sent', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contracts', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.employeecontract')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'Employee Contract',
                'verbose_name_plural': 'Employee Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('proposed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_job_title', models.CharField(blank=True, max_length=200)),
                ('proposed_terms', models.TextField(blank=True)),
                ('renewal_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('new_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_contract', to='contracts.employeecontract')),
                ('original_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='contracts.employeecontract')),
            ],
            options={
                'verbose_name': 'Contract Renewal',
                'verbose_name_plural': 'Contract Renewals',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=50)),
                ('amendment_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('description', models.TextField(help_text='Description of changes made')),
                ('previous_values', models.JSONField(blank=True, default=dict, help_text='Store previous values')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='Store new values')),
                ('amendment_document', models.FileField(blank=True, null=True, upload_to='contracts/amendments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.employeecontract')),
            ],
            options={
                'verbose_name': 'Contract Amendment',
                'verbose_name_plural': 'Contract Amendments',
                'ordering': ['-amendment_date'],
            },
        ),
    ]
