# Generated by Django 4.2.28 on 2026-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_create_contracts_for_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrenewal',
            name='proposed_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='proposed_terms',
            field=models.TextField(blank=True),
        ),
    ]
