# Generated by Django 4.2.24 on 2025-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blu_support', '0002_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link to a training video or external resource.'),
        ),
    ]
