# Generated by Django 4.2.24 on 2025-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blu_support', '0003_knowledgearticle_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='media_file',
            field=models.FileField(blank=True, help_text='Optional uploaded media (video, image or PDF) stored in the platform.', null=True, upload_to='knowledge_base/'),
        ),
    ]
