# Generated by Django 4.2.24 on 2025-10-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='benefit name')),
                ('benefit_type', models.CharField(choices=[('HEALTH_INSURANCE', 'Health Insurance'), ('DENTAL_INSURANCE', 'Dental Insurance'), ('VISION_INSURANCE', 'Vision Insurance'), ('LIFE_INSURANCE', 'Life Insurance'), ('RETIREMENT_401K', '401(k) Retirement Plan'), ('PENSION', 'Pension Plan'), ('PAID_TIME_OFF', 'Paid Time Off'), ('SICK_LEAVE', 'Sick Leave'), ('PARENTAL_LEAVE', 'Parental Leave'), ('TRANSPORT', 'Transportation Allowance'), ('MEAL_VOUCHER', 'Meal Voucher'), ('GYM_MEMBERSHIP', 'Gym Membership'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='benefit type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('company_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Amount company pays per month', max_digits=12, verbose_name='company contribution')),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Amount employee pays per month', max_digits=12, verbose_name='employee contribution')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='mandatory')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'benefit',
                'verbose_name_plural': 'benefits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base salary')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Bi-weekly'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=20, verbose_name='payment frequency')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.OneToOneField(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'salary structure',
                'verbose_name_plural': 'salary structures',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('pay_date', models.DateField(verbose_name='pay date')),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base pay')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='overtime pay')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='bonus')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='commission')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='allowances')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='tax')),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='social security')),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='insurance')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='other deductions')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='gross pay')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total deductions')),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='net pay')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payroll',
                'verbose_name_plural': 'payrolls',
                'ordering': ['-period_end', '-pay_date'],
                'unique_together': {('employee', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='enrollment date')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='payroll.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee benefit',
                'verbose_name_plural': 'employee benefits',
                'ordering': ['-enrollment_date'],
                'unique_together': {('employee', 'benefit', 'enrollment_date')},
            },
        ),
    ]
