# Generated by Django 4.2.24 on 2025-10-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='checklist name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_default', models.BooleanField(default=False, verbose_name='default checklist')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'offboarding checklist',
                'verbose_name_plural': 'offboarding checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='checklist name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_default', models.BooleanField(default=False, verbose_name='default checklist')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'onboarding checklist',
                'verbose_name_plural': 'onboarding checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='task title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20, verbose_name='priority')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('days_to_complete', models.PositiveIntegerField(default=1, verbose_name='days to complete')),
                ('assigned_to_role', models.CharField(blank=True, max_length=50, verbose_name='assigned to role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.onboardingchecklist')),
            ],
            options={
                'verbose_name': 'onboarding task',
                'verbose_name_plural': 'onboarding tasks',
                'ordering': ['checklist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('expected_completion_date', models.DateField(verbose_name='expected completion date')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='actual completion date')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_buddies', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.onboardingchecklist')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee onboarding',
                'verbose_name_plural': 'employee onboardings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_date', models.DateField(verbose_name='last working date')),
                ('reason', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End'), ('OTHER', 'Other')], default='RESIGNATION', max_length=20, verbose_name='reason')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('exit_interview_completed', models.BooleanField(default=False, verbose_name='exit interview completed')),
                ('exit_interview_notes', models.TextField(blank=True, verbose_name='exit interview notes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.offboardingchecklist')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee offboarding',
                'verbose_name_plural': 'employee offboardings',
                'ordering': ['-last_working_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='onboarding.employeeonboarding')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask')),
            ],
            options={
                'verbose_name': 'onboarding task completion',
                'verbose_name_plural': 'onboarding task completions',
                'ordering': ['task__order'],
                'unique_together': {('employee_onboarding', 'task')},
            },
        ),
    ]
