# Generated by Django 4.2.24 on 2025-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onboardingtaskcompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='offboardingchecklist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AddField(
            model_name='onboardingtaskcompletion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='offboardingchecklist',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingchecklist',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtaskcompletion',
            unique_together={('tenant', 'employee_onboarding', 'task')},
        ),
    ]
