# Generated by Django 4.2.24 on 2025-12-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcategory_tenant_assetmaintenancelog_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeasset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units for this asset record', verbose_name='quantity'),
        ),
    ]
