# Generated by Django 4.2.24 on 2025-12-25 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_alter_tenantdomain_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_employeeasset_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='employee name')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='position/department')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('signature_data', models.TextField(help_text='Base64-encoded signature image', verbose_name='signature data')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to='assets.employeeasset')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_collections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenant_management.tenant')),
            ],
            options={
                'verbose_name': 'asset collection record',
                'verbose_name_plural': 'asset collection records',
                'ordering': ['-signed_at'],
            },
        ),
    ]
