# Generated by Django 5.1.5 on 2026-03-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('blu_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('PROJECT_SUMMARY', 'Project Summary'), ('TIME_TRACKING', 'Time Tracking'), ('FINANCIAL', 'Financial Report'), ('TEAM_PRODUCTIVITY', 'Team Productivity'), ('CLIENT_ISSUES', 'Client Issues'), ('SLA_COMPLIANCE', 'SLA Compliance'), ('CUSTOM', 'Custom Query')], max_length=50)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('filters_json', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ON_DEMAND', 'On Demand')], default='ON_DEMAND', max_length=20)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, to='blu_projects.project')),
                ('recipients', models.ManyToManyField(blank=True, related_name='subscribed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Report',
                'verbose_name_plural': 'Custom Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('layout_json', models.TextField()),
                ('widgets_json', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('in_progress_tasks', models.IntegerField(default=0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_task_completion_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('team_size', models.IntegerField(default=0)),
                ('active_team_members', models.IntegerField(default=0)),
                ('client_satisfaction_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_issues_reported', models.IntegerField(default=0)),
                ('resolved_issues', models.IntegerField(default=0)),
                ('sla_compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blu_projects.project')),
            ],
            options={
                'verbose_name': 'Project Analytics',
                'verbose_name_plural': 'Project Analytics',
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_data', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='blu_analytics.customreport')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasks_assigned', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_overdue', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_task_completion_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('on_time_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('issues_assigned', models.IntegerField(default=0)),
                ('issues_resolved', models.IntegerField(default=0)),
                ('average_resolution_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_analytics', to='blu_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member Analytics',
                'verbose_name_plural': 'Team Member Analytics',
                'indexes': [models.Index(fields=['user', 'project'], name='blu_analyti_user_id_0fbdfd_idx'), models.Index(fields=['period_start', 'period_end'], name='blu_analyti_period__7bd0ca_idx')],
                'unique_together': {('user', 'project', 'period_start', 'period_end')},
            },
        ),
    ]
