# Generated by Django 4.2.24 on 2025-11-03 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blu_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(help_text='Auto-generated issue number', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CLIENT', 'Waiting for Client'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(choices=[('BUG', 'Bug/Error'), ('FEATURE', 'Feature Request'), ('SUPPORT', 'Support Question'), ('MAINTENANCE', 'Maintenance'), ('PERFORMANCE', 'Performance Issue'), ('OTHER', 'Other')], default='SUPPORT', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('response_sla_breached', models.BooleanField(default=False)),
                ('resolution_sla_breached', models.BooleanField(default=False)),
                ('attachments_count', models.IntegerField(default=0)),
                ('is_maintenance_issue', models.BooleanField(default=False, help_text='Issue during maintenance period')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_issues', to='blu_projects.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_response_time', models.IntegerField(default=2, help_text='Hours to respond to critical issues')),
                ('high_response_time', models.IntegerField(default=8, help_text='Hours to respond to high priority issues')),
                ('medium_response_time', models.IntegerField(default=24, help_text='Hours to respond to medium priority issues')),
                ('low_response_time', models.IntegerField(default=48, help_text='Hours to respond to low priority issues')),
                ('critical_resolution_time', models.IntegerField(default=8, help_text='Hours to resolve critical issues')),
                ('high_resolution_time', models.IntegerField(default=24, help_text='Hours to resolve high priority issues')),
                ('medium_resolution_time', models.IntegerField(default=72, help_text='Hours to resolve medium priority issues')),
                ('low_resolution_time', models.IntegerField(default=120, help_text='Hours to resolve low priority issues')),
                ('support_hours', models.CharField(default='9 AM - 5 PM, Mon-Fri', help_text='Support availability hours', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('maintenance_start_date', models.DateField(blank=True, help_text='Start of maintenance/warranty period', null=True)),
                ('maintenance_end_date', models.DateField(blank=True, help_text='End of maintenance/warranty period', null=True)),
                ('maintenance_terms', models.TextField(blank=True, help_text='Maintenance contract terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='blu_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note, not visible to client')),
                ('is_resolution', models.BooleanField(default=False, help_text='This comment contains the resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blu_projects.clientissue')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='issue_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blu_projects.clientissue')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('REPORT', 'Can Report Issues'), ('FULL', 'Full Access')], default='REPORT', max_length=20)),
                ('can_view_internal_notes', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='blu_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client access',
            },
        ),
        migrations.AddIndex(
            model_name='clientissue',
            index=models.Index(fields=['project', 'status'], name='blu_project_project_4b24f4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientissue',
            index=models.Index(fields=['issue_number'], name='blu_project_issue_n_9e95a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientaccess',
            unique_together={('user', 'project')},
        ),
    ]
