# Generated by Django 4.2.28 on 2026-03-01 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blu_projects', '0002_clientissue_projectsla_issuecomment_issueattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiary_count',
            field=models.IntegerField(blank=True, help_text='Number of intended beneficiaries (NGOs)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD – US Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('ZAR', 'ZAR – South African Rand'), ('KES', 'KES – Kenyan Shilling'), ('NGN', 'NGN – Nigerian Naira'), ('GHS', 'GHS – Ghanaian Cedi'), ('ZMW', 'ZMW – Zambian Kwacha'), ('TZS', 'TZS – Tanzanian Shilling'), ('UGX', 'UGX – Ugandan Shilling'), ('OTHER', 'Other')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, help_text='Donor or funding organisation', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='grant_reference',
            field=models.CharField(blank=True, help_text='Grant/contract reference number', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark as reusable template'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.CharField(blank=True, choices=[('WATERFALL', 'Waterfall'), ('AGILE', 'Agile / Scrum'), ('KANBAN', 'Kanban'), ('PRINCE2', 'PRINCE2'), ('PMI', 'PMI / PMBOK'), ('LEAN', 'Lean'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other / Custom')], default='WATERFALL', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True, help_text='Project goals and expected outcomes'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal / Operational'), ('CLIENT', 'Client / Commercial'), ('RESEARCH', 'Research & Development'), ('GRANT', 'Grant / Donor-Funded'), ('GOVERNMENT', 'Government / Public Sector'), ('INFRASTRUCTURE', 'Infrastructure / Capital'), ('IT_SOFTWARE', 'IT / Software Development'), ('CONSTRUCTION', 'Construction / Engineering'), ('EVENT', 'Event / Campaign'), ('HUMANITARIAN', 'Humanitarian / Relief'), ('CSR', 'CSR / Community'), ('OTHER', 'Other')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, help_text='What is in and out of scope'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology & ICT'), ('HEALTH', 'Health & Medical'), ('EDUCATION', 'Education & Training'), ('AGRICULTURE', 'Agriculture & Food'), ('FINANCE', 'Finance & Banking'), ('CONSTRUCTION', 'Construction & Real Estate'), ('ENERGY', 'Energy & Utilities'), ('TRANSPORT', 'Transport & Logistics'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail & Trade'), ('NGO', 'Non-Profit / NGO'), ('GOVERNMENT', 'Government & Public Admin'), ('MEDIA', 'Media & Communications'), ('LEGAL', 'Legal & Compliance'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private – Team Only'), ('INTERNAL', 'Internal – All Staff'), ('CLIENT', 'Client-Visible'), ('PUBLIC', 'Public')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(blank=True, help_text='Definition of Done / acceptance criteria'),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, choices=[('', 'No Label'), ('BUG', 'Bug'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('RESEARCH', 'Research'), ('DESIGN', 'Design'), ('TESTING', 'Testing'), ('DOCUMENTATION', 'Documentation'), ('DEVOPS', 'DevOps'), ('FIELDWORK', 'Field Work'), ('PROCUREMENT', 'Procurement'), ('REPORTING', 'Reporting')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='blu_projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Agile story points (1,2,3,5,8,13…)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('SPONSOR', 'Project Sponsor'), ('DONOR', 'Donor / Funder'), ('BENEFICIARY', 'Beneficiary'), ('CLIENT', 'Client'), ('GOVERNMENT', 'Government / Regulator'), ('PARTNER', 'Implementing Partner'), ('CONSULTANT', 'Consultant / Advisor'), ('VENDOR', 'Vendor / Supplier'), ('COMMUNITY', 'Community Representative'), ('MEDIA', 'Media'), ('OTHER', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('influence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('interest', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('engagement', models.CharField(choices=[('UNAWARE', 'Unaware'), ('RESISTANT', 'Resistant'), ('NEUTRAL', 'Neutral'), ('SUPPORTIVE', 'Supportive'), ('CHAMPION', 'Champion')], default='NEUTRAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('engagement_strategy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stakeholders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='blu_projects.project')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('FINANCIAL', 'Financial / Budget'), ('SCHEDULE', 'Schedule / Timeline'), ('RESOURCE', 'Resource / Staffing'), ('SCOPE', 'Scope Creep'), ('STAKEHOLDER', 'Stakeholder'), ('REGULATORY', 'Regulatory / Compliance'), ('SECURITY', 'Security'), ('ENVIRONMENTAL', 'Environmental'), ('DONOR', 'Donor / Funding'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('probability', models.IntegerField(choices=[(1, 'Very Low (1)'), (2, 'Low (2)'), (3, 'Medium (3)'), (4, 'High (4)'), (5, 'Very High (5)')], default=2)),
                ('impact', models.IntegerField(choices=[(1, 'Negligible (1)'), (2, 'Minor (2)'), (3, 'Moderate (3)'), (4, 'Major (4)'), (5, 'Critical (5)')], default=2)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('contingency_plan', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='blu_projects.project')),
                ('risk_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-probability', '-impact'],
            },
        ),
    ]
