# Generated by Django 4.2.24 on 2025-10-08 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_company_button_color_company_card_header_color_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_programs', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for company-wide training', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='accounts.companydepartment', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Department programs may require admin approval', verbose_name='requires admin approval'),
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=200, verbose_name='training title')),
                ('program_type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('TECHNICAL', 'Technical Skills'), ('SOFT_SKILLS', 'Soft Skills'), ('LEADERSHIP', 'Leadership'), ('COMPLIANCE', 'Compliance'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='program type')),
                ('description', models.TextField(verbose_name='description/justification')),
                ('target_employees', models.PositiveIntegerField(default=1, help_text='How many employees will attend', verbose_name='number of employees')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='estimated duration (hours)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('preferred_provider', models.CharField(blank=True, max_length=200, verbose_name='preferred provider')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('business_justification', models.TextField(help_text='Explain the business need and expected benefits', verbose_name='business justification')),
                ('urgency_reason', models.TextField(blank=True, help_text='Explain why this is urgent', verbose_name='urgency reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='approval date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_training', models.ForeignKey(blank=True, help_text='Training program created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='training.trainingprogram', verbose_name='created training program')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='accounts.companydepartment', verbose_name='department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'training request',
                'verbose_name_plural': 'training requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
